<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Security Monitor');

if(isset($_GET['DateTimeOptions']))
{
    $DateTimeOptions  = $_GET['DateTimeOptions'];
    $UserOptions      = $_GET['UserOptions'];
    $ModuleOptions    = $_GET['ModuleOptions'];
    $KeywordSearch    = $_GET['KeywordSearch'];
    $IPAddressOptions = $_GET['IPAddressOptions'];
    $TimeStart        = $_GET['TimeStart'];
    $TimeEnd          = $_GET['TimeEnd'];
    $Username         = $_GET['Username'];
    $Module           = $_GET['Module'];
    $Keyword          = $_GET['Keyword'];
    $IPAddress        = $_GET['IPAddress'];

    $settings="";
    if($DateTimeOptions=="ViewAll")
    {
        $settings.= "*No date and time range. <br />";
        $TimeFilter= "1=1";
    }
    else
    {
        $settings.= "*Start search at ". date("F d Y, g:i a",$TimeStart)." and end at ". date("F d Y, g:i a",$TimeEnd)." <br />";
        $TimeFilter = "datetime >= '" . quote_smart($TimeStart) . "' AND datetime <= '" . quote_smart($TimeEnd) . "'";
    }

    if($UserOptions=="ViewAll")
    {
        $settings.="*View all users. <br />";
        $UserFilter = "1=1";
    }
    else 
    {
        $settings.="*View only user '" . cobalt_htmlentities($Username) . "'.<br />";
        $UserFilter = "user = '" . quote_smart($Username) . "'";
    }

    if($ModuleOptions=="ViewAll")
    {
        $settings.="*View all events in all modules. <br />";
        $ModuleFilter="1=1";
    }
    else
    {
        $settings.="*View only events at module '" . cobalt_htmlentities($Module) . "'<br />";
        $ModuleFilter="module LIKE '%" . quote_smart($Module) . "%'";
    }

    if($KeywordSearch=="Off")
    {
        $settings.="*No keywords used to filter results. <br />";
        $KeywordFilter="1=1";
    }
    else
    {
        $settings.="*Used the following keyword(s) as filter: '" . cobalt_htmlentities($Keyword) . "'<br />";
        $KeywordFilter="action LIKE '%" . quote_smart($Keyword) . "%'";
    }

    if($IPAddressOptions=="Off")
    {
        $settings.="*No IP address used to filter results. <br />";
        $IPAddressFilter="1=1";
    }
    else
    {
        $settings.="*Used the following as IP address filter: '" . cobalt_htmlentities($IPAddress) . "'<br />";
        $IPAddressFilter="ip_address LIKE '%" . quote_smart($IPAddress) . "%'";
    }

    $DateTimeOptions  = cobalt_htmlentities($DateTimeOptions);
    $UserOptions      = cobalt_htmlentities($UserOptions);
    $ModuleOptions    = cobalt_htmlentities($ModuleOptions);
    $KeywordSearch    = cobalt_htmlentities($KeywordSearch);
    $IPAddressOptions = cobalt_htmlentities($IPAddressOptions);
    $TimeStart        = cobalt_htmlentities($TimeStart);
    $TimeEnd          = cobalt_htmlentities($TimeEnd);
    $Username         = cobalt_htmlentities($Username);
    $Module           = cobalt_htmlentities($Module);
    $Keyword          = cobalt_htmlentities($Keyword);
    $IPAddress        = cobalt_htmlentities($IPAddress);
}

if(!isset($start)) $start=0;

$data_con = new data_abstraction;
$data_con->set_fields("entry_id, ip_address, user, datetime, action, module");
$data_con->set_table("`system_log`");
$data_con->set_where("$TimeFilter AND $UserFilter AND $ModuleFilter AND $KeywordFilter AND $IPAddressFilter");
$data_con->set_order("entry_id");

?>
<html>
<head><title>Security Monitor :: Printer-Friendly Version</title>
</head>
<body>
<?php 
$html_writer = new html;
$html_writer->draw_page_title('Security Monitor');
echo $settings;
?>
<table border="1" width="100%" cellpadding="0" cellspacing="0">
<tr>
    <td>Entry ID</td>
    <td>IP Address</td>
    <td>User</td>
    <td>Timestamp</td>
    <td>Action</td>
    <td>Module</td>
</tr>

<?php
    if($result = $data_con->make_query()->result)
    {
        $numrows = $data_con->num_rows;

        if($numrows == 1) $record = 'record';
        else $record = 'records';

        while($row = $result->fetch_assoc())
        {
            extract($row);
            echo '<tr>
                    <td>' . cobalt_htmlentities($entry_id) . '</td>
                    <td>' . cobalt_htmlentities($ip_address) . '</td>
                    <td>' . cobalt_htmlentities($user) . '</td>
                    <td>' . date("l, F d, Y -- h:i:s a", $datetime) . '</td>
                    <td>' . nl2br(cobalt_htmlentities($action)) . '</td>
                    <td>' . cobalt_htmlentities($module) . '</td></tr>' . "\n";
        }
        $result->close();
    }
    else error_handler("Error getting log entries: ", "Query: " . $data_con->query . " -----Error: " . $data_con->error);
?>
</table>
</body>
</html>
