<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Edit resume hdr');

if(isset($_GET['id']))
{
    $id = urldecode($_GET['id']);
    require 'form_data_resume_hdr.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/resume_hdr.php';
    $dbh_resume_hdr = new resume_hdr;

    $object_name = 'dbh_resume_hdr';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_resume_hdr.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_resume_hdr->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_resume_hdr->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_resume_hdr->edit($arr_form_data);

            require_once 'subclasses/resume_dtl.php';
            $dbh_resume_hdr = new resume_dtl;
            //$dbh_resume_hdr->delete_many($arr_form_data);
			$dbh_resume_hdr->delete_data($id);

            for($a=0; $a<$resume_dtl_count;$a++)
            {
                
                $param = array(
                               'response'=>$cf_resume_dtl_response[$a],
                               'resume_hdr_id'=>$id,
                               'questionnaire_id'=>$cf_resume_dtl_questionnaire_id[$a]
                              );
                $dbh_resume_hdr->add($param);
            }


            redirect("listview_resume_hdr.php?$query_string");
        }
    }
}
require 'subclasses/resume_hdr_html.php';
$html = new resume_hdr_html;
$html->draw_header('Edit Resume Hdr', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('id');

$username = "root";
$password = "";
$hostname = "localhost"; 

//connection to the database
$dbhandle = mysql_connect($hostname, $username, $password) 
 or die("Unable to connect to MySQL");
//echo "Connected to MySQL<br>";

//select a database to work with
$selected = mysql_select_db("apc-cpo",$dbhandle) 
  or die("Could not select examples");

//execute the SQL query and return records
//$result = mysql_query("SELECT count(question) as count FROM questionnaire WHERE type = 'Resume'");
$questions = mysql_query("SELECT question FROM questionnaire WHERE type = 'Resume'");
//fetch tha data from the database 
/*while ($row = mysql_fetch_array($result)) {
    $i= $row['count'];
}*/

$n = -1;
$m = -1;

while ($row = mysql_fetch_array($questions)) {
    $z = $row['question'];
	//$r = $row['id'];
	$n++;
	$m++;
	
	
//	echo '<!DOCTYPE html><meta charset="UTF-8"><html><body>';
//	echo '<input type=text name="cf_eval_dtl_question[' . $n . ']" placeholder="' . $z . '" >';
//	echo '<input type=hidden name="cf_eval_dtl_questionnaire_id[' . $m .']" value="' . $r . '">';
	
	
	$cf_resume_dtl_question[$n] = $z;
	
//$cf_resume_dtl_questionnaire_id[$n] = $r;
	//echo '</body></html>';
}


//close the connection
mysql_close($dbhandle);

//echo $result;

//$resume_dtl_count = $i;
//$num_resume_dtl = $i;





$html->draw_controls('edit');

$html->draw_footer();