<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Add final paper hdr');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/final_paper_hdr.php';
    $dbh_final_paper_hdr = new final_paper_hdr;

    $object_name = 'dbh_final_paper_hdr';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button', $_SERVER['PHP_SELF']);
        redirect("listview_final_paper_hdr.php?$query_string");
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button', $_SERVER['PHP_SELF']);

        $file_upload_control_name = 'attachment';
        require 'components/upload_generic.php';
        $message .= $dbh_final_paper_hdr->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_final_paper_hdr->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_final_paper_hdr->add($arr_form_data);
            $id = $dbh_final_paper_hdr->auto_id;
            require_once 'subclasses/final_paper_dtl.php';
            $dbh_final_paper_hdr = new final_paper_dtl;
            for($a=0; $a<$final_paper_dtl_count;$a++)
            {
                
                $param = array(
                               'id'=>$id,
                               'final_paper_hdr_id'=>$id,
                               'questionnaire_id'=>$cf_final_paper_dtl_questionnaire_id[$a],
                               'response'=>$cf_final_paper_dtl_response[$a]
                              );
                $dbh_final_paper_hdr->add($param);
            }


            redirect("listview_final_paper_hdr.php?$query_string");
        }
    }
}
require 'subclasses/final_paper_hdr_html.php';
$html = new final_paper_hdr_html;
$html->draw_header('Add Final Paper Hdr', $message, $message_type, TRUE, TRUE);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();