<?php

function createStandardHeader($Module_Name)
{
    $content=<<<EOD
<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt($Module_Name);

EOD;
    return $content;
}
