<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Edit resume hdr');

if(isset($_GET['id']))
{
    $id = urldecode($_GET['id']);
    require 'form_data_resume_hdr.php';

}
elseif(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/resume_hdr.php';
    $dbh_resume_hdr = new resume_hdr;

    $object_name = 'dbh_resume_hdr';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button', $_SERVER['PHP_SELF']);
        redirect("listview_resume_hdr.php?$query_string");
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button', $_SERVER['PHP_SELF']);

        $message .= $dbh_resume_hdr->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_resume_hdr->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_resume_hdr->edit($arr_form_data);

            require_once 'subclasses/resume_dtl.php';
            $dbh_resume_hdr = new resume_dtl;
            $dbh_resume_hdr->del($arr_form_data);

            for($a=0; $a<$resume_dtl_count;$a++)
            {
                
                $param = array(
                               'id'=>$id,
                               'response'=>$cf_resume_dtl_response[$a],
                               'resume_hdr_id'=>$id,
                               'questionnaire_id'=>$cf_resume_dtl_questionnaire_id[$a]
                              );
                $dbh_resume_hdr->add($param);
            }


            redirect("listview_resume_hdr.php?$query_string");
        }
    }
}
require 'subclasses/resume_hdr_html.php';
$html = new resume_hdr_html;
$html->draw_header('Edit Resume Hdr', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('id');

$html->draw_controls('edit');

$html->draw_footer();